### ISSUE TITLE
Ajout configuration docker pour l'application memoryfs

### ISSUE THREAD

**Issue by mtd42** [Stephanux/memoryfs#2]
Hello Stef,
J'ai voulu testé l'application, 
Je me suis dit que ça pourrait être sympa de run mongo dans un container docker :D
J'ai testé ça fonctionne super :D
Après s'était pour mon usage personnel :) je suppose que les étudiants suivront ton tuto **Dockerize**

### Prérequis : 
- Installer docker sur sa machine
`https://www.docker.com/get-started`

### Dans le dossier `serveur/`:
- Créer fichier docker-compose.yml
```yml
version : '3.7'
services:
  mongo-db:
    container_name: mongo-db
    image: mongo:latest
    hostname: mongodb
    environment:
      # Tu peux choisir tes identifiants /!\ --auth sera activé par défaut si tu dé-commentes les deux lignes suivantes
      # MONGO_INITDB_ROOT_USERNAME: "greta"
      # MONGO_INITDB_ROOT_PASSWORD: "greta"
      MONGO_INIT_DATABASE: "gretajs"
    ports:
      - "27017:27017"
````
> Je n'ai pas fait de volumes, mais c'est carrément possible :)

### Dans le fichier `serveur/package.json`:
- Ajouter aux scripts:
```json
  "scripts": {
    "start": "node ./bin/www",
    "start:mongo": "docker-compose up -d",
    "stop:mongo": "docker-compose down"
  },
```
> Pour start:mongo tu peux enlever le -d pour ne pas lancer le container en background
